"""Guarded helpers in sound-bank padding and the unused US debug color routine."""
import json, struct
from sotn import read, HERE

BASE = 0x800A0000

def i(op, rs, rt, imm):
    return (op << 26) | (rs << 21) | (rt << 16) | (imm & 0xffff)

def words(*items):
    return b''.join(struct.pack('<I', w) for w in items)

def jump(addr, link=False):
    return ((3 if link else 2) << 26) | ((addr >> 2) & 0x3ffffff)

def guarded(offset, data, check_tunables=(), **extra):
    old = read('DRA.BIN', 'v')[offset:offset + len(data)]
    mask = bytearray(len(data))
    for start, length in [*check_tunables, *extra.get('tunable', [])]:
        mask[start:start + length] = bytes([1]) * length
    for kind in ('o', 'a'):
        actual = read('DRA.BIN', kind)[offset:offset + len(data)]
        assert len(actual) == len(data) and (actual == old or all(a == b or mask[n] for n, (a, b) in enumerate(zip(actual, data)))), (kind, hex(offset))
    return dict(file='DRA.BIN', offset=hex(offset), off=old.hex(), on=data.hex(), **extra)

def stone_edits():
    # Apply each stone's bonus once per equipped stone.
    helper = words(
        i(4, 2, 0, 15), 0, i(15, 0, 8, 0x8009), i(9, 8, 8, 0x7bc8), i(9, 8, 9, 12),
        i(33, 4, 10, 0), i(35, 8, 11, 0), 0,
        (11 << 21) | (10 << 16) | (11 << 11) | 0x21,
        i(43, 8, 11, 0), i(9, 4, 4, 2), i(5, 8, 9, -7), i(9, 8, 8, 4),
        i(9, 2, 2, -1), i(5, 2, 0, -13), i(9, 4, 4, -8), 0x03e00008, 0)
    edits = [guarded(0x13e10, helper), guarded(0x13e58, struct.pack('<8h', *([5] * 8)), tunable=[[0, 16]])]
    for start, table in ((0x54a90, 0x3e58), (0x54ad0, 0x3e60)):
        hook = words(i(15, 0, 4, 0x800b), jump(BASE + 0x13e10, True), i(9, 4, 4, table)) + bytes(32)
        edits.append(guarded(start, hook))
    return edits

def dark_extension():
    # Refresh equipment first, then add temporary STR, CON and LCK.
    code = [i(9, 29, 29, -24), i(43, 29, 31, 16), jump(0x800f4994, True), 0,
            i(15, 0, 8, 0x8007), i(33, 8, 8, 0x2f16), 0,
            i(6, 8, 0, 19), i(15, 0, 9, 0x8009)]
    values = []
    for key, at in (('str', 0x7bc8), ('con', 0x7bcc), ('lck', 0x7bd4)):
        offsets = [0x42e98 + (len(code) + n) * 4 for n in (2, 3)]
        values.append(dict(key=key, file='DRA.BIN', offset=offsets[0], offsets=offsets,
                           signed=True, editable=True, min=0, max=99, optional=True))
        code += [i(35, 9, 10, at), i(35, 9, 11, at + 16),
                 i(9, 10, 10, 0), i(9, 11, 11, 0), i(43, 9, 10, at), i(43, 9, 11, at + 16)]
    code += [i(35, 29, 31, 16), i(9, 29, 29, 24), 0x03e00008, 0]
    assert len(code) * 4 == 124
    tuning = [(offset - 0x42e98, 2) for value in values for offset in value['offsets']]
    edits = [guarded(0x42e98, words(*code), check_tunables=tuning, optional=True),
             guarded(0x553ac, words(jump(BASE + 0x42e98, True)), optional=True)]
    for edit in edits:
        edit['onAlt'] = [dict(bytes=edit['off'], tunable=[])]
    return edits, values

def write_stones():
    edits = stone_edits()
    data = dict(edits=edits, helper=0x13e10, table=0x13e58)
    out = HERE.parents[1] / 'stats-buffs-data.js'
    out.write_text('// Generated by tools/extra-hacks/build_catalog.py.\n'
                   '(function(g){const data=' + json.dumps(data, separators=(',', ':')) +
                   ';g.SotnStatBuffs=data;if(typeof module!=="undefined")module.exports=data;})(typeof window!=="undefined"?window:globalThis);\n', encoding='utf-8')
    return edits
