// Generated by tools/ass2/build-release.js from the vanilla US and ASS 2.0 BINs. Do not edit by hand.
window.SotnAss2Release = {
 "title": "Alternate Scarlet Symphony 2.0",
 "build": 7,
 "version": "2.0.07",
 "built": "2026-10-03",
 "ppf": {
  "file": "ass2/Alternate-Scarlet-Symphony-2.0.ppf",
  "name": "Alternate-Scarlet-Symphony-2.0.ppf",
  "size": 3720050,
  "sha256": "EC8C0442B3783FD88A8694FBF47B97D8956FA3CC706C986E6122C032F82D9FAD",
  "records": 187488,
  "sectors": 174204
 },
 "vanilla": {
  "name": "Castlevania - Symphony of the Night (USA) (Track 1).bin",
  "size": 538655040,
  "sha256": "CE01203A9DF93E001B88EF4C350889C19F11FFBA89D20F214BDD8DEC0B2D8D7C",
  "crc32": "05BE47B2"
 },
 "result": {
  "name": "Castlevania - Alternate Scarlet Symphony 2.0 (Track 1).bin",
  "size": 538655040,
  "sha256": "B478C2A8A9D1BE28F23A4E29068F12272023ACFFED53A282CC205B46E6C218BB",
  "crc32": "76EDAAD4"
 },
 "disc": {
  "filesChanged": 68,
  "filesTotal": 296,
  "stagesChanged": 58
 },
 "numbers": {
  "changedValues": 3523,
  "enemies": [
   168,
   168
  ],
  "hand": [
   169,
   169
  ],
  "spellRows": [
   8,
   8
  ],
  "alucard": {
   "hpMax": [
    70,
    1500
   ],
   "mpMax": [
    20,
    50
   ],
   "heartsMax": [
    50,
    1500
   ],
   "str": [
    6,
    50
   ],
   "con": [
    6,
    25
   ],
   "int": [
    6,
    50
   ],
   "lck": [
    6,
    50
   ]
  },
  "pickups": {
   "hpMaxUp": [
    5,
    50
   ],
   "heartMaxUp": [
    5,
    25
   ],
   "smallHeart": [
    1,
    10
   ],
   "bigHeart": [
    5,
    50
   ]
  },
  "potions": [
   {
    "name": "Potion",
    "vanilla": 50,
    "ass": 300,
    "cost": 300,
    "costHearts": true
   },
   {
    "name": "High Potion",
    "vanilla": 100,
    "ass": 800,
    "cost": 700,
    "costHearts": true
   },
   {
    "name": "X-Potion",
    "vanilla": 0,
    "ass": 2500,
    "cost": 1500,
    "costHearts": true
   }
  ],
  "soulSteal": [
   8,
   67
  ],
  "mistDrain": [
   10,
   1
  ],
  "bosses": [
   {
    "name": "Dracula",
    "hp": [
     10000,
     32000
    ],
    "attack": [
     39,
     666
    ]
   },
   {
    "name": "Shaft",
    "hp": [
     1300,
     26666
    ],
    "attack": [
     40,
     500
    ]
   },
   {
    "name": "Death",
    "hp": [
     1200,
     22000
    ],
    "attack": [
     40,
     555
    ]
   },
   {
    "name": "Galamoth",
    "hp": [
     12000,
     32000
    ],
    "attack": [
     50,
     999
    ]
   },
   {
    "name": "Beelzebub",
    "hp": [
     2000,
     32000
    ],
    "attack": [
     60,
     455
    ]
   },
   {
    "name": "Richter Belmont",
    "hp": [
     400,
     20000
    ],
    "attack": [
     25,
     0
    ]
   },
   {
    "name": "Karasuman",
    "hp": [
     500,
     20000
    ],
    "attack": [
     20,
     723
    ]
   },
   {
    "name": "Medusa",
    "hp": [
     1100,
     15000
    ],
    "attack": [
     35,
     272
    ]
   },
   {
    "name": "Akmodan II",
    "hp": [
     1200,
     15000
    ],
    "attack": [
     40,
     285
    ]
   },
   {
    "name": "Olrox",
    "hp": [
     666,
     15000
    ],
    "attack": [
     20,
     200
    ]
   },
   {
    "name": "Succubus",
    "hp": [
     666,
     12000
    ],
    "attack": [
     25,
     230
    ]
   },
   {
    "name": "Fake Trevor",
    "hp": [
     1200,
     10000
    ],
    "attack": [
     38,
     0
    ]
   }
  ],
  "subweapons": [
   {
    "name": "Dagger",
    "cost": [
     1,
     5
    ],
    "attack": [
     5,
     20
    ]
   },
   {
    "name": "Axe",
    "cost": [
     4,
     15
    ],
    "attack": [
     10,
     100
    ]
   },
   {
    "name": "Holy Water",
    "cost": [
     3,
     30
    ],
    "attack": [
     1,
     1
    ]
   },
   {
    "name": "Cross",
    "cost": [
     100,
     150
    ],
    "attack": [
     5,
     5
    ]
   },
   {
    "name": "Bible",
    "cost": [
     5,
     20
    ],
    "attack": [
     8,
     50
    ]
   },
   {
    "name": "Stopwatch",
    "cost": [
     20,
     200
    ],
    "attack": [
     0,
     0
    ]
   },
   {
    "name": "Rebound Stone",
    "cost": [
     2,
     10
    ],
    "attack": [
     8,
     80
    ]
   },
   {
    "name": "Vibhuti",
    "cost": [
     3,
     13
    ],
    "attack": [
     8,
     25
    ]
   },
   {
    "name": "Agunea",
    "cost": [
     5,
     20
    ],
    "attack": [
     10,
     80
    ]
   }
  ],
  "spells": [
   {
    "name": "Dark Metamorphosis",
    "mp": [
     10,
     20
    ],
    "attack": [
     0,
     0
    ]
   },
   {
    "name": "Summon Spirit",
    "mp": [
     5,
     30
    ],
    "attack": [
     15,
     250
    ]
   },
   {
    "name": "Hellfire",
    "mp": [
     15,
     40
    ],
    "attack": [
     30,
     400
    ]
   },
   {
    "name": "Tetra Spirit",
    "mp": [
     20,
     70
    ],
    "attack": [
     15,
     200
    ]
   },
   {
    "name": "Wolf Charge",
    "mp": [
     10,
     15
    ],
    "attack": [
     30,
     511
    ]
   },
   {
    "name": "Soul Steal",
    "mp": [
     50,
     99
    ],
    "attack": [
     15,
     155
    ]
   },
   {
    "name": "Wing Smash",
    "mp": [
     8,
     40
    ],
    "attack": [
     50,
     511
    ]
   },
   {
    "name": "Sword Brothers",
    "mp": [
     30,
     50
    ],
    "attack": [
     20,
     529
    ]
   }
  ]
 }
};
